### ISSUE TITLE
Find out, whether it is better to use RabbitMQ for network transfer.

### ISSUE THREAD

**Issue by LukasForst** [LukasForst/pibe-java-api#22]

**Comment by marekklement** [comment]
..▓▓..▓▓
..▓▓......▓▓
..▓▓......▓▓..................▓▓▓▓
..▓▓......▓▓..............▓▓......▓▓▓▓
..▓▓....▓▓..............▓......▓▓......▓▓
....▓▓....▓............▓....▓▓....▓▓▓....▓▓
......▓▓....▓........▓....▓▓..........▓▓....▓
........▓▓..▓▓....▓▓..▓▓................▓▓
........▓▓......▓▓....▓▓
.......▓......................▓
.....▓.........................▓
....▓......^..........^......▓
....▓............♥.............▓
....▓..........................▓
......▓..........ٮ..........▓
..........▓▓..........▓▓
